[window]
opacity = 0.8

[font]
size = 13
#normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
normal = { family = "OpenDyslexicM Nerd Font Mono", style = "Regular" }

[colors.primary]
background = "#000000"
foreground = "#D8DEE9"

[colors.normal]
black = "#000000" # Overriden default CachyOS with black instead
red = "0xBF616A"
green = "0xA3BE8C"
yellow = "0xEBCB8B"
blue = "0x81A1C1"
magenta = "0xB48EAD"
cyan = "0x88C0D0"
white = "0xE5E9F0"

[colors]
draw_bold_text_with_bright_colors = true
transparent_background_colors = true

