[window]
opacity = 0.8

[font]
size = 13
#normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
normal = { family = "OpenDyslexicM Nerd Font Mono", style = "Regular" }

[colors.primary]
background = "#000000"
foreground = "#D8DEE9"

[colors]
draw_bold_text_with_bright_colors = true
transparent_background_colors = true

